#!/usr/bin/env node

import { Command } from 'commander';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

dotenv.config();

const packageJson = JSON.parse(
  readFileSync(join(__dirname, '../package.json'), 'utf8')
);

const program = new Command();

program
  .name('precommit-hook')
  .description('Pre-commit hook manager - automate code checks before every commit')
  .version(packageJson.version);

// Install hook
program
  .command('install')
  .description('Install pre-commit hook')
  .option('--skip-tests', 'Skip running tests')
  .option('--skip-lint', 'Skip linting')
  .option('--max-files <n>', 'Max files to check', '50')
  .action(async (options) => {
    const fs = await import('fs');
    const path = await import('path');
    
    const gitDir = join(process.cwd(), '.git');
    if (!existsSync(gitDir)) {
      console.error('❌ Not a git repository');
      process.exit(1);
    }
    
    const hooksDir = join(gitDir, 'hooks');
    if (!existsSync(hooksDir)) {
      mkdirSync(hooksDir, { recursive: true });
    }
    
    const hookPath = join(hooksDir, 'pre-commit');
    
    const hookContent = `#!/bin/sh
# Pre-commit Hook - Auto Code Check
# Generated by precommit-hook-manager

echo "🔍 Running pre-commit checks..."

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | head -${options.maxFiles || 50})

if [ -z "$STAGED_FILES" ]; then
  echo "No files to check"
  exit 0
fi

echo "Checking $STAGED_FILES"

${options.skipLint ? '# Lint check disabled' : `
echo "Running lint check..."
for file in $STAGED_FILES; do
  if [ -f "$file" ]; then
    echo "  Checking: $file"
  fi
done
`}

${options.skipTests ? '# Test check disabled' : `
echo "Running tests..."
npm test 2>/dev/null || echo "Tests not configured"
`}

echo "✅ Pre-commit checks complete"
exit 0
`;
    
    writeFileSync(hookPath, hookContent);
    
    // Make executable
    try {
      execSync('chmod +x "' + hookPath + '"', { stdio: 'ignore' });
    } catch {}
    
    console.log('✅ Pre-commit hook installed!');
    console.log(`   Location: ${hookPath}`);
    console.log('\nThe hook will run before each commit.');
  });

// Uninstall hook
program
  .command('uninstall')
  .description('Remove pre-commit hook')
  .action(async () => {
    const hookPath = join(process.cwd(), '.git', 'hooks', 'pre-commit');
    
    if (!existsSync(hookPath)) {
      console.log('No pre-commit hook found');
      return;
    }
    
    const fs = await import('fs');
    fs.unlinkSync(hookPath);
    console.log('✅ Pre-commit hook removed');
  });

// List hooks
program
  .command('list')
  .description('List installed hooks')
  .action(async () => {
    const hooksDir = join(process.cwd(), '.git', 'hooks');
    
    if (!existsSync(hooksDir)) {
      console.log('No hooks directory found');
      return;
    }
    
    const fs = await import('fs');
    const files = fs.readdirSync(hooksDir);
    
    console.log('📌 Installed hooks:\n');
    for (const file of files) {
      const isPreCommit = file === 'pre-commit';
      console.log(`${isPreCommit ? '✅' : '📄'} ${file}`);
    }
  });

// Check current staged files
program
  .command('check')
  .description('Check staged files without committing')
  .option('--max-files <n>', 'Max files to check', '50')
  .action(async (options) => {
    try {
      const staged = execSync('git diff --cached --name-only --diff-filter=ACM', { encoding: 'utf-8' });
      const files = staged.trim().split('\n').filter(Boolean);
      
      if (files.length === 0) {
        console.log('No staged files');
        return;
      }
      
      console.log(`📋 ${files.length} staged file(s):\n`);
      for (const file of files.slice(0, parseInt(options.maxFiles))) {
        console.log(`  - ${file}`);
      }
      
      if (files.length > parseInt(options.maxFiles)) {
        console.log(`\n  ... and ${files.length - parseInt(options.maxFiles)} more`);
      }
    } catch (error) {
      console.log('Not a git repository or no staged files');
    }
  });

// GitHub Actions integration
program
  .command('action')
  .description('Generate GitHub Actions workflow')
  .action(async () => {
    const fs = await import('fs');
    const path = await import('path');
    
    const workflowDir = join(process.cwd(), '.github', 'workflows');
    mkdirSync(workflowDir, { recursive: true });
    
    const workflowContent = `name: Pre-commit Checks

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install deps
        run: npm install
      
      - name: Check staged files
        run: |
          echo "Checking staged files..."
          git diff --cached --name-only --diff-filter=ACM
`;
    
    writeFileSync(join(workflowDir, 'precommit.yml'), workflowContent);
    console.log('✅ Created .github/workflows/precommit.yml');
  });

program.parse();
